apiVersion: v1
kind: ConfigMap
metadata:
  name: user-url
data:
  ORDER_SERVICE_URL: 'http://order.default.svc:8080'
  PRODUCT_SERVICE_URL: 'http://product.default.svc:8080'
  CART_SERVICE_URL: 'http://cart.default.svc:8080'
  RATING_SERVICE_URL: 'http://rating.default.svc:8080'
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db
data:
  MYSQL_ID: 'root'
  MYSQL_ROOT_PASSWORD: 'root' ## TODO secret으로 빼기 
  MYSQL_DB: 'user'
  MYSQL_HOST: 'user-db.default.svc'
