apiVersion: v1
kind: Service
metadata:
  name:  user
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 8080
      targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: user-db
